package interfaces;

import java.awt.Color;
import java.awt.Container;

/**
 *
 * @author Armando Salazar
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private final Container fondo = this.getContentPane();
    panelMenu pm = new panelMenu();
    panelVentas pv = new panelVentas();
    panelMantenimiento pma = new panelMantenimiento();
    panelReportes pr = new panelReportes();
    

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        fondo.setBackground(new Color(255, 217, 0));
        initComponents();
        panelContenedor.add(pm);
        pm.setVisible(true);
        pv.setVisible(false);
        pma.setVisible(false);
        pr.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        btnMenu = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnMantenimiento = new javax.swing.JButton();
        btnResportes = new javax.swing.JButton();
        panelCerrar = new javax.swing.JPanel();
        cerrarLB = new javax.swing.JLabel();
        panelMinimizar = new javax.swing.JPanel();
        minimizarLB = new javax.swing.JLabel();
        panelContenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panelPrincipal.setBackground(new java.awt.Color(255, 0, 44));

        btnMenu.setBackground(new java.awt.Color(255, 0, 44));
        btnMenu.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(255, 217, 0));
        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu.png"))); // NOI18N
        btnMenu.setText(" Menú");
        btnMenu.setBorder(null);
        btnMenu.setContentAreaFilled(false);
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu.png"))); // NOI18N
        btnMenu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menuG.png"))); // NOI18N
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        btnVentas.setBackground(new java.awt.Color(255, 0, 44));
        btnVentas.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        btnVentas.setForeground(new java.awt.Color(255, 217, 0));
        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tienda.png"))); // NOI18N
        btnVentas.setText(" Ventas");
        btnVentas.setBorder(null);
        btnVentas.setContentAreaFilled(false);
        btnVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVentas.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tienda.png"))); // NOI18N
        btnVentas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tiendaG.png"))); // NOI18N
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });

        btnMantenimiento.setBackground(new java.awt.Color(255, 0, 44));
        btnMantenimiento.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        btnMantenimiento.setForeground(new java.awt.Color(255, 217, 0));
        btnMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ui.png"))); // NOI18N
        btnMantenimiento.setText(" Mantenimiento");
        btnMantenimiento.setBorder(null);
        btnMantenimiento.setContentAreaFilled(false);
        btnMantenimiento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMantenimiento.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ui.png"))); // NOI18N
        btnMantenimiento.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/uiG.png"))); // NOI18N
        btnMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMantenimientoActionPerformed(evt);
            }
        });

        btnResportes.setBackground(new java.awt.Color(255, 0, 44));
        btnResportes.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        btnResportes.setForeground(new java.awt.Color(255, 217, 0));
        btnResportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/crecimiento.png"))); // NOI18N
        btnResportes.setText(" Reportes");
        btnResportes.setBorder(null);
        btnResportes.setContentAreaFilled(false);
        btnResportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResportes.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/crecimiento.png"))); // NOI18N
        btnResportes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/crecimientoG.png"))); // NOI18N
        btnResportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResportesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnResportes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnVentas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMantenimiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addContainerGap(277, Short.MAX_VALUE)
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnResportes, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        panelCerrar.setBackground(new java.awt.Color(255, 0, 44));

        cerrarLB.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        cerrarLB.setForeground(new java.awt.Color(255, 255, 255));
        cerrarLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrarLB.setText("X");
        cerrarLB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrarLB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarLBMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelCerrarLayout = new javax.swing.GroupLayout(panelCerrar);
        panelCerrar.setLayout(panelCerrarLayout);
        panelCerrarLayout.setHorizontalGroup(
            panelCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cerrarLB, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );
        panelCerrarLayout.setVerticalGroup(
            panelCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCerrarLayout.createSequentialGroup()
                .addComponent(cerrarLB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelMinimizar.setBackground(new java.awt.Color(255, 0, 44));

        minimizarLB.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        minimizarLB.setForeground(new java.awt.Color(255, 255, 255));
        minimizarLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizarLB.setText("_");
        minimizarLB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizarLB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarLBMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelMinimizarLayout = new javax.swing.GroupLayout(panelMinimizar);
        panelMinimizar.setLayout(panelMinimizarLayout);
        panelMinimizarLayout.setHorizontalGroup(
            panelMinimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMinimizarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(minimizarLB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelMinimizarLayout.setVerticalGroup(
            panelMinimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMinimizarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(minimizarLB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelContenedor.setBackground(new java.awt.Color(255, 217, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 947, Short.MAX_VALUE)
                        .addComponent(panelMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1344, 705));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarLBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarLBMouseClicked
        System.exit(0);
    }//GEN-LAST:event_cerrarLBMouseClicked

    private void minimizarLBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarLBMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_minimizarLBMouseClicked

    private void btnMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMantenimientoActionPerformed
        pm.setVisible(false);
        pv.setVisible(false);
        pma.setVisible(true);
        pr.setVisible(false);
        panelContenedor.add(pma);
    }//GEN-LAST:event_btnMantenimientoActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        pm.setVisible(true);
        pv.setVisible(false);
        pma.setVisible(false);
        pr.setVisible(false);
        panelContenedor.add(pm);
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        pm.setVisible(false);
        pv.setVisible(true);
        pma.setVisible(false);
        pr.setVisible(false);
        panelContenedor.add(pv);
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnResportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResportesActionPerformed
        pm.setVisible(false);
        pv.setVisible(false);
        pma.setVisible(false);
        pr.setVisible(true);
        panelContenedor.add(pr);       
    }//GEN-LAST:event_btnResportesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMantenimiento;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnResportes;
    private javax.swing.JButton btnVentas;
    private javax.swing.JLabel cerrarLB;
    private javax.swing.JLabel minimizarLB;
    private javax.swing.JPanel panelCerrar;
    private javax.swing.JPanel panelContenedor;
    private javax.swing.JPanel panelMinimizar;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
